# Generated by Django 5.0.2 on 2024-02-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_event_event_id_alter_eventregistration_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregistration',
            name='name',
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
